version: "3.9"
services:

  pokemon-service:
    container_name: pokemon-app
    image: pokemon-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    tty:
      true
    restart:
      unless-stopped