name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: ${{github.repository}}/pokemon-orquestracao-dados
          tags: latest, ${{github.run_number}}

      #Login Funciona
      #- name: Login Docker Hub
          #uses: docker/login-action@v1
          #with:
            #username: ${{secrets.DOCKER_USER}}
            #password: ${{secrets.DOCKER_PASSWORD}}
            #logout: true

      #Não Funciona publicar docker-compose.yaml
      #- name: Docker-Compose Publish
        #uses: pennsignals/publish_docker-compose@v0.1.1
        #with:
          #version: ${{github.run_number}}
          #docker_compose: docker-compose.yaml
          #repo_token: "${{ secrets.GITHUB_TOKEN }}"
