name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Docker Publish
      uses: ${{secrets.DOCKER_USER}}/pokemon-orquestracao-dados:@v0.1.0
      with:
        docker_compose: 'docker-compose.yaml' # required
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        
